---
# Install beats package on debian based distributions.

- name: Install metricbeat deb package.
  apt: deb="https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-{{ beats_package_version }}-amd64.deb" state=present
  notify:
    - enable beat
    - restart beat
