---
# Install Beats package on redhat based distributions.

- name: Install {{ beats_package_name }} rpm package.
  yum: name="https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-{{ beats_package_version }}-x86_64.rpm"
  notify:
    - enable beat
    - restart beat
